language: python
python:
- 3.6
install:
- make install
script:
- make lint
- make validate-template
env:
  global:
  - secure: Cw3sideKeF/6pHPSLuIAdAr/e6JPFkuypcz0uVPj9ZqL53df03cFohr/f1MygTb5PTZpyzq+QzoP5VA6e1RQDS4dhQMSi+85KfpMikWAXoP5I2AJ1IEY8MTXERCMoUWNg4WGmxt0BtyXt/WnHIRN3rgzMft4irfJJhYGjSeHZ5Arv2sCBOkrsFyl8kXqYtaLT1n4b8z7OuSOPuMrrNCl0xbJaPvPwGSMF4kJzWWcXAqnpKsdsgQfbNrNwAUgkZkzxVlMJ1shQu7/euHECFONJP+nzWh3xplVOE8mEgtTmOXDN87sSOG/IZnNPfgM0kjhusxLHogbomtTnEIov+XUoEuO5zoHPn1v+e1HflnO/IbFmno342ybmvB2DMw9M5ek54ljHaOaJVh7/vVSLXluqya9yMIctQHCA1oZ5XZ5eN43DRWoZDDazh5AT8/AhBeKibKnnX/sI37vJTs52rphlBuJaOwNWTR7qFkF0HeabDqTHlSUFj6l1FOnBSrKi4LEgTWtqO+2lq7/GZtdWpPmoulJJqmLbF4wKae4y9F1z720f8ys+0V5zR2Ydh5afCyEN5RHJztbZXvIM4AbnvxtH/pqirpvRGNN7hH0bopPAcn0EfdW1v4d2aWmXTamWxYW4i796ohmIx4UivgPyfxLYGFOzfSnvBLRBP+XQQQDPdk=
  - secure: dFVgDTAxa8PRQdVAIHjkeCQ6yDwicHxX3y1+gjJY/Ol29ELXu8xFqHtk7hwBjQFNNrfnOzhqqE+VY5hadMycVKwHZclYbsemkZk3gCuTIPFVTchPWtoZqF5VbyYieJtTIVq/ixfbqLO80wz2+eyIcwlvFCLhKESRtb+5f6XppmmxWEB6UdimmGK4JtV+RP1KIzeeWCAsT8GdqH587StIsZ1+AVwQT4QNUohb2flR6FZRMYzu74ZWKQ7e501lywl1918M4u/Qwvr7JyKXzFfGGTAloeXnrIdX8o5ru/jWIX9VCiKLsArc5K3pIHFTprDLjvczZsK/6ZeGyB+pz6foi7X7Cr/wu2TU+Ge3vU9gOrF0YNenpGxX2rob6mD1QBb69/S6me5T5Ob1tqAF90VxElOGm2KO7ZGXHKGV9hJ9HrSccbYR/j4yISEa01uA4qVRkp7warjwlItkJVHAwnM4+R5Lp7lkgWaEaygFWBf+uj6tqgdixUp9zANnAURsPvC//xoqDbdHgmnn9D+BOXGCK1Osubw5Y6+59/MKmhNKuKnVdWR1XA4SSsn6qsBi8/f1M3C5N5ndHEo+MB71+Jz6uzrpiKkiZGY7mmP0AdPIQoiTtCEs5VDfd8k9rLJ92gGqtcwETki/6tuxxG6Qh1w70xHzmYeSE8ZfkWXxUjwLZJY=
