---
AWSTemplateFormatVersion: '2010-09-09'

Description: >-
  Create a central S3 bucket and SNS topic for CloudTrail.

Parameters:
  BucketName:
    Type: String
    Description: Enter S3 bucket name
    AllowedPattern: ^[a-z0-9][-a-z0-9]{1,61}[a-z0-9]$
  TopicName:
    Type: String
    Description: Enter SNS topic name
    AllowedPattern: ^[-_a-zA-Z0-9]{3,256}$

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:GetBucketAcl'
            Resource: !GetAtt Bucket.Arn
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Join ['', !GetAtt Bucket.Arn, '/AWSLogs/*']
            Condition:
              StringLike:
                's3:x-xml-acl': 'bucket-owner-full-control'

  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName

  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref Topic
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 'SNS:Publish'
            Resource: !Ref Topic

Outputs:
  CloudTrailBucket:
    Description: Name of CloudTrail S3 bucket
    Value: !Ref Bucket
    Export:
      Name: CloudTrail-Bucket
  CloudTrailTopic:
    Description: Name of CloudTrail SNS topic
    Value: !Ref Topic
    Export:
      Name: CloudTrail-Topic
